const express = require("express")

const router = express.Router()

const AdmissionRouter=require("./Admission.routes")
const BlogRouter=require("./Blog.routes")
const CardRouter=require("./Card.routes")
const CartRoutes=require("./Cart.routes")
const categoryRouter=require("./Category.routes")
const CertificateRoutes=require("./Certificate.routes")
const ContentRoutes=require("./Content.routes")
const CoupanRoutes=require("./Coupan.routes")
const CourseRoutes=require("./Course.routes")
const PaymentRoutes=require("./Payment.routes")
const ProgressRoutes=require("./Progress.rotes")
const Quiz_ContentRoutes=require("./Quiz_Content.routes")
const QuizRoutes=require("./Quiz.routes")
const ResultRoutes=require("./Result.routes")
const ReviewRoutes=require("./Review.routes")
const SectionRoutes=require("./Section.routes")
const Term_ConditionRoutes=require("./Term&Conditin.routes")    
const UserRoutes=require("./User.routes")
const WhishlistRoutes=require("./Whishlist.routes")

//http://localhost:8080/api/v1/category
router.use('/admission',AdmissionRouter)
router.use('/blog',BlogRouter)
router.use('/card',CardRouter)
router.use('/cart',CartRoutes)
router.use('/category',categoryRouter)
router.use('/certificate',CertificateRoutes)
router.use('/content',ContentRoutes)
router.use('/coupan',CoupanRoutes)
router.use('/course',CourseRoutes)
router.use('/payment',PaymentRoutes)
router.use('/progress',ProgressRoutes)
router.use('/quiz_content',Quiz_ContentRoutes)
router.use('/quiz',QuizRoutes)
router.use('/result',ResultRoutes)
router.use('/review',ReviewRoutes)
router.use('/section',SectionRoutes)
router.use('/term&condition',Term_ConditionRoutes)
router.use('/user',UserRoutes)
router.use('/whishlist',WhishlistRoutes)


module.exports = router